type: object
additionalProperties: false
properties:
    ui:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
            subDomain:
                type: string
        required:
            - enabled
            - subDomain
            - domain
    api:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
            subDomain:
                type: string
        required:
            - enabled
            - subDomain
            - domain
    vault:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
            subDomain:
                type: string
        required:
            - enabled
            - subDomain
            - domain
    recursor:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
            subDomain:
                type: string
        required:
            - enabled
            - subDomain
            - domain
    nodes:
        type: array
        minItems: 1
        items:
            type: object
            additionalProperties: false
            required:
                - name
            properties:
                main:
                    type: boolean
                ips:
                    type: array
                    minItems: 1
                    items:
                        type: string
                legacyIps:
                    type: array
                    minItems: 1
                    items:
                        type: string
                name:
                    type: string
                ansible:
                    $ref: "#/definitions/AnsibleConfig"

                setup:
                    type: object
                    additionalProperties: false
                    required:
                        - system
                        - root
                        - cloneRepo
                        - setup
                        - start
                    properties:
                        system:
                            type: string
                        root:
                            type: object
                            additionalProperties: false
                            properties:
                                disableSystemdResolved:
                                    type: boolean
                                installDocker:
                                    type: boolean
                            required:
                                - disableSystemdResolved
                                - installDocker
                        cloneRepo:
                            type: boolean
                        setup:
                            type: boolean
                        start:
                            type: boolean

    nameservers:
        type: array
        minItems: 1
        # one nameserver (for each domain) must have the main attribute set to true
        items:
            - type: object
              additionalProperties: false
              required:
                  - domain
                  - node
              properties:
                  subDomain:
                      type: string
                  domain:
                      type: string
                  node:
                      type: string
                  main:
                      type: boolean

    registrarApi:
        type: object
        required:
            - enabled
        properties:
            enabled:
                type: boolean
            registrars:
                type: array
                minItems: 1
                items:
                    type: object
                    additionalProperties: false
                    required:
                        - registrar
                        - domains
                        - secretPath
                    properties:
                        registrar:
                            enum: [gandi]
                        domains:
                            type: array
                            minItems: 1
                            items:
                                type: string
                        secretPath:
                            type: string

    certificates:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            letsencryptEmail:
                type: string
        required:
            - enabled
            - letsencryptEmail
    reverseProxy:
        type: object
        additionalProperties: false
        properties:
            createTraefik:
                type: boolean
            applyTraefikConfig:
                type: boolean
        required:
            - createTraefik
            - applyTraefikConfig
    build:
        type: object
        additionalProperties: false
        required:
            - server
            - api
            - ui
        properties:
            server:
                type: object
                additionalProperties: false
                properties:
                    enabled:
                        type: boolean
                    path:
                        type: string
                required:
                    - enabled
                    - path
            api:
                type: object
                additionalProperties: false
                properties:
                    enabled:
                        type: boolean
                    path:
                        type: string
                required:
                    - enabled
                    - path
            ui:
                type: object
                additionalProperties: false
                properties:
                    enabled:
                        type: boolean
                    path:
                        type: string
                required:
                    - enabled
                    - path

    devmode:
        type: object
        additionalProperties: false
        required:
            - enabled
            - type
        properties:
            enabled:
                type: boolean
            type:
                enum: [local, insecure-online]

    ansible:
        type: object
        additionalProperties: false
        required:
            - sshKey
        properties:
            sshKey:
                type: object
                additionalProperties: false
                properties:
                    pubKeyPath:
                        type: string
                    pubKeyName:
                        type: string
                required:
                    - pubKeyPath
                    - pubKeyName

required:
    - ui
    - api
    - vault
    - recursor
    - nodes
    - registrarApi
    - certificates
    - reverseProxy
    - build
    - devmode
    - nameservers
# either ansible or nodes are required
definitions:
    AnsibleConfigType:
        type: string
        enum: [hetzner]

    AnsibleConfig:
        oneOf:
            - { $ref: "#/definitions/Hetzner" }

    Hetzner:
        type: object
        additionalProperties: false
        required:
            - configType
        properties:
            configType:
                $ref: "#/definitions/AnsibleConfigType"
            floatingIp:
                type: boolean
            floatingLegacyIp:
                type: boolean
            location:
                type: string
                enum: [nbg1, fsn1]
            serverType:
                $ref: "#/definitions/HetznerServerType"

    HetznerServerType:
        type: string
        enum: [cx11, cpx11, cx21, cpx21, cx31, cpx31, cx41, cpx41, cx51, cpx51]
