"$schema": https://json-schema.org/draft/2020-12/schema
title: Pektin Config
description: Pektin configuration file specification
type: object
additionalProperties: false
required:
    - domain
    - nameServers
properties:
    domain:
        type: string
        description: The main domain you want to use for your DNS server, api etc.
    nameServers:
        type: array
        items:
            type: object
            additionalProperties: false
            required:
                - subDomain
                - ips
                - legacyIps
            properties:
                subDomain:
                    type: string
                ips:
                    type: array
                    items:
                        type: string
                legacyIps:
                    type: array
                    items:
                        type: string
                createSingleScript:
                    type: object
                    additionalProperties: false
                    required:
                        - system
                    properties:
                        system:
                            enum:
                                - ubuntu
                                - arch
                        root:
                            type: object
                            additionalProperties: false
                            description: options that require root priviliges on the arbeiter machine
                            properties:
                                disableSystemdResolved:
                                    type: boolean
                                    description: run a helper script to disable systemd resolved on
                                        ubuntu machines (if systemd-resolved is present it needs to either
                                        be stopped manually or automatically becuase it's blocking port
                                        53)
                                installDocker:
                                    type: boolean
                                    description: will add docker installation script
                        cloneRepo:
                            type: boolean
                            description: whether or not cloning the compose repo should be included
                                in the single script
                        setup:
                            type: boolean
                            description: whether or not to run the setup script
                        start:
                            type: boolean
                            description: whether or not to run the start script
        description: The subdomains you want to use for your nameservers; the first will
            be the primary name server running the ui, api, vault etc.; all other servers
            are additional nameserver only running pektin-server, redis and traefik
    multiNode:
        type: boolean
        description: whether or not to run on multiple hosts
    uiSubDomain:
        type: string
        description: The subdomain you want to use for accessing the user interface (if
            enabled)
    apiSubDomain:
        type: string
        description: The subdomain you want to use for accessing Pektin API (if enabled)
    vaultSubDomain:
        type: string
        description: The subdomain you want to use for accessing vault
    recursorSubDomain:
        type: string
        description: The subdomain you want to use for accessing the recursor (if enabled)
    enableUi:
        type: boolean
        description: Whether or not to enable the UI
    enableApi:
        type: boolean
        description: Whether or not to enable the API
    enableRecursor:
        type: boolean
        description: Whether or not to enable the private recursor
    enableRotate:
        type: boolean
        description: Whether or not to auto rotate dns keys at the registrar
    createCerts:
        type: boolean
        description: Whether or not to create certificates for the domains hosted on pektin
    letsencryptEmail:
        type: string
        description: Required if createCerts is true
    configureMainDomain:
        type: boolean
        description: create soa ns aaaa and a records for main domain on pektin after
            installation (Use registrar API to auto configure the necessary glue and ns
            records for your main domain)
    proxyConfig:
        enum:
            - none
            - traefik
        description: What proxy config to apply to the containers
    createProxy:
        type: boolean
        description: Whether or not to create the proxy container itself
    buildFromSource:
        type: boolean
        description: Whether or not to build the pektin containers from source
    sources:
        type: object
        additionalProperties: false
        description: where to pull the sources from; if unset will be pulled from github;
            will only be used if buildFromSource is set to true
        required:
            - server
            - api
            - ui
        properties:
            server:
                type: string
                description: the source path for building the server container
            api:
                type: string
                description: the source path for building the api container
            ui:
                type: string
                description: the source path for building the ui container
    dev:
        enum:
            - local
            - insecure-online
        description: Whether or not to run in development mode and if yes in what dev
            mode
