type: object
additionalProperties: false
properties:
    ui:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
        required:
            - enabled
            - domain
    api:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
        required:
            - enabled
            - domain
    vault:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
        required:
            - enabled
            - domain
    recursor:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            domain:
                type: string
        required:
            - enabled
            - domain
    nodes:
        type: array
        minItems: 1
        items:
            type: object
            additionalProperties: false
            required:
                - name
            properties:
                main:
                    type: boolean
                ips:
                    type: array
                    minItems: 1
                    items:
                        type: string
                legacyIps:
                    type: array
                    minItems: 1
                    items:
                        type: string
                name:
                    type: string
                setup:
                    type: object
                    additionalProperties: false
                    properties:
                        system:
                            type: string
                        root:
                            type: object
                            additionalProperties: false
                            properties:
                                disableSystemdResolved:
                                    type: boolean
                                installDocker:
                                    type: boolean
                            required:
                                - disableSystemdResolved
                                - installDocker
                        cloneRepo:
                            type: boolean
                        setup:
                            type: boolean
                        start:
                            type: boolean
                    required:
                        - system
                        - root
                        - cloneRepo
                        - setup
                        - start
    nameservers:
        type: array
        minItems: 1
        # one nameserver (for each domain) must have the main attribute set to true
        items:
            - type: object
              additionalProperties: false
              properties:
                  subDomain:
                      type: string
                  domain:
                      type: string
                  node:
                      type: string
                  main:
                      type: boolean
              required:
                  - domain
                  - node
    registrarApi:
        type: object
        required:
            - enabled
        properties:
            enabled:
                type: boolean
            registrars:
                type: array
                minItems: 1
                items:
                    type: object
                    additionalProperties: false
                    properties:
                        registrar:
                            enum: [gandi]
                        domains:
                            type: array
                            minItems: 1
                            items:
                                - type: string
                        secretPath:
                            type: string
                    required:
                        - registrar
                        - domains
                        - secretPath
    certificates:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            letsencryptEmail:
                type: string
        required:
            - enabled
            - letsencryptEmail
    reverseProxy:
        type: object
        additionalProperties: false
        properties:
            createTraefik:
                type: boolean
            applyTraefikConfig:
                type: boolean
        required:
            - createTraefik
            - applyTraefikConfig
    build:
        type: object
        additionalProperties: false
        properties:
            server:
                type: object
                additionalProperties: false
                properties:
                    enabled:
                        type: boolean
                    path:
                        type: string
                required:
                    - enabled
                    - path
            api:
                type: object
                additionalProperties: false
                properties:
                    enabled:
                        type: boolean
                    path:
                        type: string
                required:
                    - enabled
                    - path
            ui:
                type: object
                additionalProperties: false
                properties:
                    enabled:
                        type: boolean
                    path:
                        type: string
                required:
                    - enabled
                    - path
        required:
            - server
            - api
            - ui
    devmode:
        type: object
        additionalProperties: false
        properties:
            enabled:
                type: boolean
            type:
                enum: [local, insecure-online]
        required:
            - enabled
            - type
required:
    - ui
    - api
    - vault
    - recursor
    - nodes
    - registrarApi
    - certificates
    - reverseProxy
    - build
    - devmode
