/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PektinConfig {
  ui: {
    enabled: boolean;
    domain: string;
    subDomain: string;
  };
  api: {
    enabled: boolean;
    domain: string;
    subDomain: string;
  };
  vault: {
    enabled: boolean;
    domain: string;
    subDomain: string;
  };
  recursor: {
    enabled: boolean;
    domain: string;
    subDomain: string;
  };
  nodes: {
    main?: boolean;
    ips?: [string, ...string[]];
    legacyIps?: [string, ...string[]];
    name: string;
    setup?: {
      system: string;
      root: {
        disableSystemdResolved: boolean;
        installDocker: boolean;
      };
      cloneRepo: boolean;
      setup: boolean;
      start: boolean;
    };
  }[];
  nameservers?: [
    {
      subDomain?: string;
      domain: string;
      node: string;
      main?: boolean;
    }
  ];
  registrarApi: {
    enabled: boolean;
    registrars?: [
      {
        registrar: "gandi";
        domains: [string];
        secretPath: string;
      },
      ...{
        registrar: "gandi";
        domains: [string];
        secretPath: string;
      }[]
    ];
    [k: string]: unknown;
  };
  certificates: {
    enabled: boolean;
    letsencryptEmail: string;
  };
  reverseProxy: {
    createTraefik: boolean;
    applyTraefikConfig: boolean;
  };
  build: {
    server: {
      enabled: boolean;
      path: string;
    };
    api: {
      enabled: boolean;
      path: string;
    };
    ui: {
      enabled: boolean;
      path: string;
    };
  };
  devmode: {
    enabled: boolean;
    type: "local" | "insecure-online";
  };
}
